we-oauth2:
  additional:
    clientsDetails:
      - clientId: api-mortgage-app
        clientSecret: $2a$10$jU1f5TPFuYQWm/X4jPWOMO2LtrjOck7sdtsUjSoINoba.rYzEt2oG # mortgage-app-secret
        resourceIds:
          - vst-oauth2
          - vst-identity
          - vst-files
          - mortgage-app
        scope:
          - read
          - vst-client
        authorizedGrantTypes:
          - password
          - refresh_token
        registeredRedirectUri:
          - http://localhost/test
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ

      - clientId: mortgage-app
        clientSecret: $2a$10$UhvZwRRF./pfijHSpoxzX.OwqDSRL.J5RmW5lPySoFGO6y4DR7Nce # mortgage-app-secret
        resourceIds:
          - vst-identity
          - vst-files
          - vst-oauth2
        scope:
          - read
        authorizedGrantTypes:
          - client_credentials
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ
          - WE_IDENTITY_WRITE
          - WE_PRIVACY_READ
          - WE_PRIVACY_WRITE
          - WE_OAUTH2_WRITE
          - WE_OAUTH2_READ
