info:
  name: "@project.name@"
  version: "@project.version@"
  description: "@project.description@"
  parent: "@project.parent@"

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          time_zone: UTC
          log.warnings: true
          lob.non_contextual_creation: true
  application:
    name: mortgage-app
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: mortgage-app-jpa-pool
      max-lifetime: 100000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/db_mortgage_app
    username: postgres
    password: password
  flyway:
    enabled: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 100ms, 150ms, 250ms, 500ms, 1s
  health:
    rabbit:
      enabled: false
  info:
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'

security:
  oauth2:
    resource:
      id: mortgage-app
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh+sA8O8616X/nYByQ2xu
          hhFHmec3k6urgNOphfxmZ/JQ6ySdD8hnVAqUHpKwUJkd1Nad2zKp0j4DFLw6UZTz
          yXo4vdPo7Ibn3h8qPqmL7DDciWuVhJ6r1Gxajn+VohqAeLIOkIALzgN2yBjGQYws
          mjrZUmk5N7A4DuHd/PksoYjRMCoISfKfjtmx9LfCHOvqivEaCCEXcEv8vMpcnPd+
          yqQ8cUb6ya5CKdSzO82ZivIzeiJ5pvuHAmh1KsWYoqpJ82zHrdwaTElWeiN1hMv2
          wHykww+DMm/E04oeIhDoEnyyS7wvqsOC8tJo9nMnNoc93INfeICEojEi3RX2Mtwb
          PQIDAQAB
          -----END PUBLIC KEY-----
    client:
      id: mortgage-app
      client-id: mortgage-app
      client-secret: mortgage-app-secret
      access-token-uri: ${vst-oauth.url}/oauth/token
      resource-ids: vst-identity,vst-files
      grant-type: client_credentials

feign:
  retryer:
    maxAttempts: 5
    period: 60000
    maxPeriod: 900000
  client:
    config:
      vst-identity:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      vst-files:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

mortgage:
  contract: 3JPjoQkM6pLsmKESGuPHw1f6kPFvX4GPwfpsLcnDAx4U

contracts:
  sender: 3N3JPVkUkR9DTy97sixBdQj48DYfiyEFx32
  nodeAlias: node-0
  fee: 0
  config:
    mortgage:
      image: registry.weintegrator.com/mortgage-sc/mortgage-contract-app:0.0.0-SNAPSHOT-20210925061441-a2055cf
      imageHash: 82593583a6b9ec46f28a6345e4a68db428954aee5d8e0eac07dd70e5ba55ee4e

node:
  config:
    node-0:
      url: https://mortgage-dev.weintegrator.com/node-0
      xApiKey: svupkey
      nodeOwnerAddress: 3N3JPVkUkR9DTy97sixBdQj48DYfiyEFx32
      nodeOwnerPubKey: 2qcMD2JjPhbJimgVD1kyHXc2E7DbksrWmw8E8r5f3hv7tejqxkw2VudcmQGXj8AKyRPYnzQ55KDbG2uQT51fkruK
      keyStorePassword: 3PjRHdbXWbBo9QUY
    node-1:
      url: https://mortgage-dev.weintegrator.com/node-1
      xApiKey: svupkey
      nodeOwnerAddress: 3MsQ3qpkqUpoUAmfskRWYQotiZ4qf56WBve
      nodeOwnerPubKey: 4GDWWx48DeriEEvHRUwjFz1x1a6fdkAazMdxgnWQEdNgNoHsENNNwpQ82XjczEuRuQdppp2oh5yqDJe44epiu5am
      keyStorePassword: 3PjRHdbXWbBo9QUY
    node-2:
      url: https://mortgage-dev.weintegrator.com/node-2
      xApiKey: svupkey
      nodeOwnerAddress: 3MpPEoTnh5SsBFK2fCqoKtKCu67LYc8aeV8
      nodeOwnerPubKey: 271j1Qsz5sMYHWUWN3RpehrdsQHsMtxDMk7KfN5dbDZGbi6VTQXXbjHf4T2NzNxJHS9Rww74qyMnBXhDK8FgGFmH
      keyStorePassword: 3PjRHdbXWbBo9QUY

tx-observer:
  syncHistory: false

vst-oauth:
  url: https://mortgage-dev.weintegrator.com/api/v0/vst-oauth2

vst-identity:
  url: https://mortgage-dev.weintegrator.com/api/v0/vst-identity


swagger:
  basePath: /
  oauth-url: ${vst-oauth.url}/oauth/token
  basePackage: com.wavesplatform.we.app.mortgage
  securityInfo:
    clientId: demo-client

logging:
  level:
    com.wavesplatform.vst.api: DEBUG
